name: 打包发布
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '0.0.1'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: build_web
        run: npm run build:web

      - name: Compress files
        run: |
          tar -czf web_dist.tar.gz client/web/dist
          ls

      - name: Upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: web_dist.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
